micronaut:
  application:
    name: tecsaleSub
#Cassandra
cassandra:
  default:
    advanced:
      metadata:
        schema:
          enabled: false
    basic:
      contact-points:
        - "127.17.0.3:9042"
      port: 9042
      load-balancing-policy:
        local-datacenter: datacenter1
#Nats
nats:
    addresses:
      - "nats://localhost:4222"
    username: guest
    password: guest